PHONE_NUMBER_REGEX: !ruby/regexp /(84|0[3|5|7|8|9])+([0-9]{8})\b/i
ID_CARD_REGEX: !ruby/regexp /([0-9]{9})||([0-9]{8})\b/i

validate:
  length:
    digist_255: 255
    digist_2: 2
    digist_6: 6
    length_min: 8
    length_medium: 50
    length_max: 255
    length_normal: 140
    price_min: 50
    quantity_min: 10
size:
  size_avatar: 120
paginate_size: 5
banner:
  lock: 'lock'
  unlock: 'unlock'
